package dev.topo.app;

import java.util.ArrayList;
import java.util.List;

/**
 * Graph → {@code .topo} emission.
 *
 * <p>A deterministic mapping, not inference: a logic chain A→B→C becomes a
 * flow with those edges; the emitter only states edges, never stage numbers
 * (flow body accepts pipeline edges only — the stage topology is core
 * PipelineAnalysis's job).
 *
 * <p>The Java host spells stdlib scalars with the bare core names ({@code i64}
 * / {@code f64} / {@code bool} / {@code string}) and emits <em>no</em> {@code
 * using} preamble. That is the deliberate per-host decision: unlike the Python
 * host (whose scalar aliases differ from the core names and therefore need a
 * {@code using ... = std::python::...} preamble), the Java host's handler/flow
 * surface is exactly the form the handler_flow spec fixtures use, so emitting
 * the bare names both parses under the fresh grammar and round-trips.
 *
 * <p>The output is human-readable and hand-editable by construction — the
 * decisive round-trip constraint — so layout favours a stable, obvious shape
 * over compactness.
 */
public final class Emitter {

    private Emitter() {
    }

    public static String emit(Graph graph) {
        List<String> lines = new ArrayList<>();
        lines.add("// Generated by topo-app (Java). Human-readable and");
        lines.add("// round-trip safe: editing this file and reading it back");
        lines.add("// yields the same logic graph. It is a view, not an IR.");
        lines.add("");
        lines.add("namespace " + graph.namespace() + " {");
        lines.add("  public:");
        for (Handler h : graph.handlers()) {
            lines.add("    " + h.signature());
        }
        Flow flow = graph.flow();
        if (flow != null) {
            lines.add("");
            lines.add("    flow " + flow.name() + " {");
            for (Edge e : flow.edges()) {
                String tgt = e.isTerminal() ? "void" : e.target();
                lines.add("      " + e.source() + " -> " + tgt + ";");
            }
            lines.add("    }");
        }
        lines.add("}");
        lines.add("");
        return String.join("\n", lines);
    }
}
